require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/submodels", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Submodel. As you add validations to Submodel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Submodel.create! valid_attributes
      get submodels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      submodel = Submodel.create! valid_attributes
      get submodel_url(submodel)
      expect(response).to be_successful
    end
  end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_submodel_url
  #     expect(response).to be_successful
  #   end
  # end

  describe "GET /edit" do
    it "renders a successful response" do
      submodel = Submodel.create! valid_attributes
      get edit_submodel_url(submodel)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Submodel" do
        expect {
          post submodels_url, params: { submodel: valid_attributes }
        }.to change(Submodel, :count).by(1)
      end

      it "redirects to the created submodel" do
        post submodels_url, params: { submodel: valid_attributes }
        expect(response).to redirect_to(submodel_url(Submodel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Submodel" do
        expect {
          post submodels_url, params: { submodel: invalid_attributes }
        }.to change(Submodel, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post submodels_url, params: { submodel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested submodel" do
        submodel = Submodel.create! valid_attributes
        patch submodel_url(submodel), params: { submodel: new_attributes }
        submodel.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the submodel" do
        submodel = Submodel.create! valid_attributes
        patch submodel_url(submodel), params: { submodel: new_attributes }
        submodel.reload
        expect(response).to redirect_to(submodel_url(submodel))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        submodel = Submodel.create! valid_attributes
        patch submodel_url(submodel), params: { submodel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested submodel" do
      submodel = Submodel.create! valid_attributes
      expect {
        delete submodel_url(submodel)
      }.to change(Submodel, :count).by(-1)
    end

    it "redirects to the submodels list" do
      submodel = Submodel.create! valid_attributes
      delete submodel_url(submodel)
      expect(response).to redirect_to(submodels_url)
    end
  end
end
